apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin-account1
  namespace: kube-system

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
         app: vault   
  template:
    metadata:
      labels:
        app: vault          
    spec:
      serviceAccountName: admin-account
      containers:
      - name: vault
        image: 749029227687.dkr.ecr.us-east-1.amazonaws.com/vault:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000       
